### ISSUE TITLE
how can we deal selenium chrome driver on the github workflow testing

### ISSUE THREAD

**Issue by umjammer** [umjammer/vavi-nio-file-dropbox#2]
```java
##[error]Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: The driver executable does not exist: /home/runner/work/java7-fs-dropbox/java7-fs-dropbox/bin/chromedriver
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:146)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:141)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:35)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:159)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:355)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:94)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at vavi.net.auth.oauth2.dropbox.SeleniumAuthUI.openUI(SeleniumAuthUI.java:83)
	at vavi.net.auth.oauth2.dropbox.SeleniumAuthUI.lambda$auth$0(SeleniumAuthUI.java:64)
```

**Comment by umjammer** [comment]
https://stackoverflow.com/questions/35867102/how-to-work-with-selenium-chrome-driver-in-maven-without-chromedriver-exe
